// src/app/components/productsData.ts
import { ProductType } from './ProductGrid';

const myProducts: ProductType[] = [
  {
    _id: '1',
    name: 'Kuru İncir',
    price: 100,
    imageUrl: '/assets/incir/incir-1.png',
    images: ['/assets/incir/incir-1.png'],
    slug: 'kuru-incir',
    star: '4.2',
    categoryName: 'heroImage',
    description: 'Doğal kuru incir, İncirin en doğal hali',
    price_id: 'price_1',
  },
  {
    _id: '2',
    name: 'Taze İncir',
    price: 120,
    imageUrl: '/assets/incir/incir-2.png',
    images: ['/assets/incir/incir-2.png'],
    slug: 'taze-incir',
    star: '4.0',
    categoryName: 'incir',
    description: "Taze incir. Aydın'ın dağlarından toplanan en taze ürünler.",
    price_id: 'price_2',
  },
  {
    _id: '3',
    name: 'Siyah Zeytin',
    price: 80,
    imageUrl: '/assets/zeytin/zeytin-1.png',
    images: ['/assets/zeytin/zeytin-1.png'],
    slug: 'siyah-zeytin',
    star: '4.5',
    categoryName: 'Zeytin',
    description: 'Siyah zeytin.',
    price_id: 'price_3',
  },
  {
    _id: '4',
    name: 'Yeşil Zeytin',
    price: 90,
    imageUrl: '/assets/zeytin/zeytin-2.png',
    images: ['/assets/zeytin/zeytin-2.png'],
    slug: 'yesil-zeytin',
    star: '4.7',
    categoryName: 'Zeytin',
    description: 'Yeşil zeytin.',
    price_id: 'price_4',
  },
  {
    _id: '5',
    name: 'Sofralık Zeytin',
    price: 190,
    imageUrl: '/assets/zeytin/zeytin-3.png',
    images: ['/assets/zeytin/zeytin-3.png'],
    slug: 'sofralik-zeytin',
    star: '4.6',
    categoryName: 'Zeytin',
    description: 'Sofralık zeytin.',
    price_id: 'price_5',
  },
  {
    _id: '6',
    name: 'Zeytin Yağı',
    price: 90,
    imageUrl: '/assets/zeytin-yagi/zeytin-yagi-2.png',
    images: ['/assets/zeytin-yagi/zeytin-yagi-2.png'],
    slug: 'zeytin-yagi',
    star: '4.9',
    categoryName: 'Zeytin Yağı',
    description: 'Doğal zeytin yağı.',
    price_id: 'price_6',
  },
];

export default myProducts;
